### ISSUE TITLE
Segfault in PyEpics

### ISSUE THREAD

**Issue by agerasev** [agerasev/pyepics-asyncio#2]
Occur while connecting to multiple PVs concurrently (within the same event loop).

```gdb
Thread 19 "CAC-TCP-recv" received signal SIGSEGV, Segmentation fault.

#0  0x00000000005e3392 in ?? ()
#1  0x00000000005458a3 in ?? ()
#2  0x000000000053ac2c in PyObject_Vectorcall ()
#3  0x000000000052b940 in _PyEval_EvalFrameDefault ()
#4  0x000000000055c931 in _PyFunction_Vectorcall ()
#5  0x000000000053ac2c in PyObject_Vectorcall ()
#6  0x00007ffff644c147 in ?? () from /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so
#7  0x00007ffff644c088 in ?? () from /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so
#8  0x00007ffff6430d95 in ?? () from /lib/x86_64-linux-gnu/libffi.so.8
#9  0x00007ffff6431110 in ?? () from /lib/x86_64-linux-gnu/libffi.so.8
#10 0x00007fffec447fab in oldSubscription::current (this=<optimized out>, guard=..., type=0, count=1, pData=0x7fffb4017928) at ../oldSubscription.cpp:68
#11 0x00007fffec4268b2 in cac::eventRespAction (this=0x1300400, iiu=..., hdr=..., pMsgBdy=0x7fffb4017928) at ../cac.cpp:968
#12 0x00007fffec43c356 in tcpiiu::processIncoming (this=0x7fffb4000f10, currentTime=..., mgr=...) at ../tcpiiu.cpp:1264
#13 0x00007fffec4400d9 in tcpRecvThread::run (this=0x7fffb4000ff8) at ../tcpiiu.cpp:519
#14 0x00007fffcac3b4a9 in epicsThreadCallEntryPoint (pPvt=0x7fffb4001000) at ../../../src/libCom/osi/epicsThread.cpp:83
#15 0x00007fffcac417ec in start_routine (arg=0x7fffb40172b0) at ../../../src/libCom/osi/os/posix/osdThread.c:403
#16 0x00007ffff7d28044 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#17 0x00007ffff7da85fc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by agerasev** [comment]
Probably fixed by f644d946fb7e958c847f41429148eca70dd38512
